version: '2'
services:
  php-fpm:
    build: php-fpm
    image: liyu/php-fpm
    volumes_from:
        - www_data
    links:
      - mariadb
    restart: on-failure:3
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - www_data
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    links:
      - php-fpm
    restart: on-failure:3
  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=admin
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    restart: on-failure:3
  www_data:
      image: tianon/true
      volumes:
        - ./www:/var/www/html

