version: '2'
services:
  php-fpm:
    build: php-fpm
    image: liyu/php-fpm
    volumes_from:
        - volumes_www
    links:
      - mariadb
    restart: on-failure:3
  php-cli-daemon:
    build: php-cli-daemon
    image: liyu/php-cli-daemon
    volumes_from:
        - volumes_www
    volumes:
        - ./php-cli-daemon/config:/etc/supervisor.d
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - volumes_www
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - /opt/gitlab:/opt/gitlab
      - /var/opt/gitlab:/var/opt/gitlab
      - /mnt/wwwlogs:/mnt/wwwlogs
    links:
      - php-fpm
    restart: on-failure:3
  mariadb:
    image: mariadb:latest
    ports: 
      - "3307:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure:3
  volumes_www:
      image: tianon/true
      volumes:
        - /mnt/www:/var/www/html
